name: SAYAN-NUXT-Strapi
services:
  fronted:
    build: 
      context: ../frontend
      dockerfile: ../dev-config/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/usr/app
      - frontend_node_modules:/usr/app/node_modules
    environment:
      NUXT_PUBLIC_STRAPI_URL: ${NUXT_PUBLIC_STRAPI_URL}
      NUXT_STRAPI_TOKEN: ${NUXT_STRAPI_TOKEN}
      NODE_ENV: development
    networks:
      - strapi
  cms:
    build: 
      context: ../cms
      dockerfile: ../dev-config/Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ../cms:/usr/app
      - cms_node_modules:/usr/app/node_modules
    environment: 
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      STRAPI_TOKEN: ${NUXT_STRAPI_TOKEN}
      STRAPI_URL: ${NUXT_PUBLIC_STRAPI_URL}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_CLIENT: mysql
      DATABASE_PORT: 3306
      DATABASE_SSL: "false"
      NODE_ENV: development
    networks:
      - strapi
  db: 
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/mysql
    networks:
      - strapi

networks:
  strapi:
volumes:
  db:
  frontend_node_modules:
  cms_node_modules:



